server:
  port: 8086

spring:
  application:
    name: order-server
  profiles:
    active: dev
  datasource:
    name: order
    initialSize: 0
    maxActive: 20
    minIdle: 1
    maxWait: 10000
    validationQuery: select 'x'
    testOnBorrow: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 18800
    filters: stat,wall
    url: jdbc:mysql://127.0.0.1:3306/microservice?useUnicode=true&characterEncoding=utf8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 
    timeout: 3000
    jedis:
      pool:
        maxActive: 20
        maxWait: 3000
        maxIdle: 20
        minIdle: 0
  rabbimq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true

mybatis-plus:
    mapper-locations: classpath:/mybatis/mapper/*.xml
    typeAliasesPackage: com.white.orderserver.pojo.entity
    global-config:
       id-type: 2
       field-strategy: 2
       db-column-underline: true
       refresh-mapper: true
#       capital-mode: true
#       key-generator:
       logic-delete-value: 0
       logic-not-delete-value: 0
       sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
       meta-object-handler:
    configuration:
       map-underscore-to-camel-case: true
       cache-enabled: false

druid:
  loginUsername:
  loginPassword:
  resetEnable: true

#elasticsearch:
  #host: 127.0.0.1
  #port: 9200
  #pool: 5
  #cluster:
   # name: es-dev

logging:
  level:
    org.springframework.web: debug
    #com.wkclz.cas: debug
