spring:
  profiles:
    active: dev
  servlet:
    multipart:
      maxFileSize: 1MB
      maxRequestSize: 10MB


##### client & service 公用配置 #####

# Tomcat specifics
tomcat:
  accessLogEnabled: false
  protocolHeader: x-forwarded-proto
  remoteIpHeader: x-forwarded-for
  basedir:
  backgroundProcessorDelay: 30

# 参考：https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md
pagehelper:
  reasonable: true

##### client  #####
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

##timeout config
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 240000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true


#### 系统建康状态 #####
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    servlet:
      contextPath: /
    ssl:
      enabled: false
  endpoint:
    health:
      showDetails: always
    shutdown:
      enabled: true
